### ISSUE TITLE
Create html markup for the header region (excluding the menu)

### ISSUE THREAD

**Issue by marychris** [Luukyb/drupalcampcebu2018#10]
A. Use bootstrap classes in your markup.
B. Use mediaquery breakpoints in your sass for a mobile-first approach.

**Comment by nhiieL** [comment]
![drupalcampwebdesign-v1 0](https://user-images.githubusercontent.com/36254805/37610005-84500604-2bd9-11e8-819f-20a0c753513c.jpg)
