### ISSUE TITLE
Unresponsive Sponsor Now button

### ISSUE THREAD

**Issue by robertlakas** [Luukyb/drupalcampcebu2018#24]
**Context**
On mobile size screen less than 400 pixel the button text doesn't respond well.

Screenshot:
![screen shot 2018-03-28 at 8 46 04 pm](https://user-images.githubusercontent.com/37871304/38029707-3341a9c4-32c9-11e8-89df-e88972cd47a0.png)

**Solution**
Remove or lessen the `link-btn`'s left and right margin. 

Screenshot:
![screen shot 2018-03-28 at 8 56 32 pm](https://user-images.githubusercontent.com/37871304/38030201-89f77cf2-32ca-11e8-99b6-63c86ed55c53.png)

**Comment by Luukyb** [comment]
Thanks @alvincases
