### ISSUE TITLE
Create new sub theme of Bootstrap in Drupal 8

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/drupalcampcebu2018#31]
A: In the drupal folder, create a symlink of the css, sass, and js folder from static

B: Define the classy theme: 
https://www.drupal.org/docs/8/theming-drupal-8/defining-a-theme-with-an-infoyml-file

C: Create a subtheme of classy:
https://www.drupal.org/docs/8/theming-drupal-8/creating-a-drupal-8-sub-theme-or-sub-theme-of-sub-theme

3. Export the configuration of the site with the sub-theme as a default theme.
For exporting configuration use $ drush cex

Please confirm @Luukyb

**Comment by nhiieL** [comment]
Error on running composer require drupal/bootstrap
Command used: composer require drupal/bootstrap
Location: /home/junel/docker/drupalcampcebu2018/drupalcampcebu2018/drupal
Error message: 
![ss](https://user-images.githubusercontent.com/36254805/38378392-20ee4fa8-3930-11e8-8b08-07ac79d72c37.png)
